//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.abc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="abc.IStudentdataservice")]
    public interface IStudentdataservice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentdataservice/GetstudentdatausingDBwithconfig", ReplyAction="http://tempuri.org/IStudentdataservice/GetstudentdatausingDBwithconfigResponse")]
        System.Data.DataSet GetstudentdatausingDBwithconfig();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentdataservice/GetstudentdatausingDBwithconfig", ReplyAction="http://tempuri.org/IStudentdataservice/GetstudentdatausingDBwithconfigResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetstudentdatausingDBwithconfigAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentdataserviceChannel : Business.abc.IStudentdataservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentdataserviceClient : System.ServiceModel.ClientBase<Business.abc.IStudentdataservice>, Business.abc.IStudentdataservice {
        
        public StudentdataserviceClient() {
        }
        
        public StudentdataserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentdataserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentdataserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentdataserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetstudentdatausingDBwithconfig() {
            return base.Channel.GetstudentdatausingDBwithconfig();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetstudentdatausingDBwithconfigAsync() {
            return base.Channel.GetstudentdatausingDBwithconfigAsync();
        }
    }
}
